# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShearGear' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShearGear
  pod 'IQKeyboardManagerSwift', '~>4.0.8'
  pod 'MBProgressHUD'
  pod 'SendGrid', :git => 'https://github.com/scottkawai/sendgrid-swift.git'
  pod "SHMultipleSelect"
  pod 'IDMPhotoBrowser'
  pod 'NTMonthYearPicker'

end
